workflows:
  build-flutter:
    name: Build flutter
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events: # List the events that trigger builds
        - push
      branch_patterns: # Include or exclude watched branches
        - pattern: '*'
          include: true
          source: true
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build appbundle --debug
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - lila.selin@yale.edu
  hello-world:
    name: Hello world workflow
    scripts:
      - echo "Hello World!"